### PR TITLE
Remote Video

### PR DESCRIPTION
**Pull request by joewhitsitt**
Threw this together over lunch. No biggie. Uses 8.6's remote video/oembed and includes YouTube and Vimeo

- Needs testing and review.

### CODE REVIEW

**Comment by briand44** [comment]
I suggest we clean up the form a little like we did with images. We should probably reuse the media browser and/or media library form displays and remove authored on, authored by, url alias and published. I don't remember the reasoning for both of those form displays right now. I'll try and figure that out.

**Comment by joewhitsitt** [comment]
I've cleaned up the forms a bit, made sure it still works, and set view mode sizes based on some specs I saw for YouTube videos on the Internet.

There is an issue about responsive videos https://www.drupal.org/project/drupal/issues/2998091 so I think this might be blocked until this solution comes or we do something locally.

**Comment by joewhitsitt** [comment]
I have handled the responsive videos locally for now: https://github.com/uiowa/uiowa_bootstrap/pull/49

**Comment by joewhitsitt** [comment]
This is now "Remote Video" to match the media type that Drupal Core's Standard profile ships with.

**Pull request merged**
